/gps/particle opticalphoton
/gps/polarization 0 0 1 # dummy polarization

/gps/energy 2.00 eV # Red photon (No WLS)
#/gps/energy 2.36 eV #Green photon
#/gps/energy 2.95 eV #blue photon
#/gps/energy 3.4 eV
#/gps/energy 4.96 eV #250 nm
#/gps/energy 12 eV
#/gps/energy 15.5 eV # 80 nm

#/gps/position 0 0.650 0 cm #
#/gps/position 0 5 0 cm #
#/gps/position -10.1 0 0 cm
#/gps/position 9.9 0 0 cm
/gps/position 0 0 0 cm

#/gps/ang/type beam1d
/gps/ang/type iso

#/gps/direction 0 -1 0
#/gps/direction 1 0 0

/LightCollection/run/setFileName output/singleFiberTest
/LightCollection/det/fiberHalfLength 100 cm
/run/beamOn 100000

#/LightCollection/det/fiberHalfLength 1 cm
#/LightCollection/run/setFileName output/fiberAtten_1cm
#/run/beamOn 10000

#/LightCollection/det/fiberHalfLength 5 cm
#/LightCollection/run/setFileName output/fiberAtten_5cm
#/run/beamOn 10000

#/LightCollection/det/fiberHalfLength 10 cm
#/LightCollection/run/setFileName output/fiberAtten_10cm
#/run/beamOn 10000

#/LightCollection/det/fiberHalfLength 50 cm
#/LightCollection/run/setFileName output/fiberAtten_50cm
#/run/beamOn 10000

#/LightCollection/det/fiberHalfLength 100 cm
#/LightCollection/run/setFileName output/fiberAtten_100cm
#/run/beamOn 10000

#/LightCollection/det/fiberHalfLength 200 cm
#/LightCollection/run/setFileName output/fiberAtten_200cm
#/run/beamOn 10000

#/LightCollection/det/fiberHalfLength 500 cm
#/LightCollection/run/setFileName output/fiberAtten_500cm
#/run/beamOn 10000

#/LightCollection/det/fiberHalfLength 700 cm
#/LightCollection/run/setFileName output/fiberAtten_700cm
#/run/beamOn 10000

#/LightCollection/det/fiberHalfLength 1000 cm
#/LightCollection/run/setFileName output/fiberAtten_1000cm
#/run/beamOn 10000